### ISSUE TITLE
Hashes for Joomla! 4.4.4.

### ISSUE THREAD

**Issue by peterpeter** [cavo789/aesecure_quickscan#5]
Hi
The hashes for Joomla 4.4.4 are missing so far, correct?
https://prnt.sc/yj5YPKwk1N7N

We have a customer website with suspicious behavior that I would like to scan with your script.

Is there anything I could help you to generate those hashes?

Regards
Roger

**Comment by cavo789** [comment]
Hello Roger 

I'll take time to add these hashes asap...

Now, for info, you can use QuickScan even when no hashes are found... The tool will "only" scan everything since he won't be able to recognize files (untouched) coming from Joomla.

So more files to scan and probably more false positive.

**Comment by peterpeter** [comment]
Hi Christophe
Thank you very much - I'll give it a try

**Comment by peterpeter** [comment]
At the moment, getting the files ends in a Request-Timeout
https://prnt.sc/JZr8fy8jpAJ3
Yesterday getting the files was flawless.

I'll try it later again ;-)

**Comment by cavo789** [comment]
Hi

I've added missing hashes up to J5.1.0.

**Comment by peterpeter** [comment]
Grrrreat, thank you very much!
